# global_frame: utm_odom
# rolling_window: true
# cost_scaling_factor: 20.0
# mark_threshold: 5
# plugins:
#   - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
#   - {name: inflation,                 type: "costmap_2d::InflationLayer"}

local_costmap:
  global_frame: utm_odom
  map_topic: utm_odom
  robot_base_frame: base_link
  track_unknown_space: true

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 6
  height: 6
  resolution: 0.05