footprint: [[-0.75, -0.31], [0.63, -0.31], [0.63, 0.31], [-0.75, 0.31]]
#footprint: [[-2, -2], [2, -2], [2, 2], [-2, 2]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 5.0

resolution: 0.05

obstacle_range: 4.0 # was 6.5
raytrace_range: 8.0 # was 7.0
cost_scaling_factor: 20.0

#layer definitions
static:
    enabled: false
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    enabled: true
    observation_sources: None #pointcloud
    #pointcloud: {sensor_frame: os_lidar, data_type: PointCloud2, clearing: true, marking: true, topic: ouster/points, min_obstacle_height: 0.7, max_obstacle_height: 1.0, footprint_clearing_enabled: false,inf_is_valid: true, track_unknown_space: false, comination_method: 1} # Could set a max obstacle height

inflation:
    enabled: false
    inflation_radius: 0.0
