footprint: [[-0.48, -0.23], [0.48, -0.23], [0.48, 0.23], [-0.48, 0.23]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 4.0 # was 6.5
raytrace_range: 4.0 # was 7.0

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: pointcloud
    pointcloud: {sensor_frame: os_lidar, data_type: PointCloud2, clearing: true, marking: true, topic: ouster/points, min_obstacle_height: 0.6} # Could set a max obstacle height

inflation:
    inflation_radius: 1.0
