global_frame: utm_odom
rolling_window: true
cost_scaling_factor: 20.0
mark_threshold: 5
plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
