# global_frame: utm_odom
# rolling_window: false
# track_unknown_space: true

# plugins:
#   - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
#   - {name: inflation,               type: "costmap_2d::InflationLayer"}

global_costmap:
  global_frame: utm_odom
  robot_base_frame: base_link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  width: 100.0
  height: 100.0
  origin_x: -50.0
  origin_y: -50.0

  static_map: true