status_topic: "/autonomy_manager/status"
sensor_prep_status_topic: "/sensor_prep_status"
joy_topic: "/joy"
gps_topic: '/gps_avg'
sensor_prep_service_name: '/run_sensor_prep'
deploy_service_name: '/autonomy_manager/deploy_autonomy'
goal_reach_service_name: 'goal_reach'
clear_service_name: 'clear'
pxrf_service_name: 'pxrf_complete'
waypoints_service_name: 'waypoints'
grid_points_service_name: 'grid_points'
next_goal_service_name: 'next_goal'
next_goal_nav_service_name: 'next_goal_nav'