# Autonomy Manager
status_topic: '/autonomy_manager/status'
set_search_boundary_name: '/autonomy_manager/set_search_boundary'
clear_service_name: 'clear'
waypoints_service_name: 'waypoints'
grid_points_service_name: 'grid_points'
lower_arm_service_name: 'lower_arm'                             # Used in GUI
manager_run_loop_service_name: 'manager_run_loop'
manager_set_status_after_error_param_name: 'manager/set_status_after_error'
start_utm_x_param: 'start_utm_x'
start_utm_y_param: 'start_utm_y'
start_utm_lat_param: 'start_utm_lat'
start_utm_lon_param: 'start_utm_lon'
algorithm_type_param_name: algorithm_type                       
algorithm_type: adaptive                                        # Used in GUI           
algorithm_total_samples: 16                                     # Used in GUI
sim_mode: false

# GUI (gui.py)
goal_pub_topic: '/gps_navigation/goal'
gps_sub_topic: '/heading_true'
parking_break_service_name: '/parking_brake'
pxrf_client_topic_name: '/take_measurement'
gps_moving_avg_topic: '/gps_moving_avg'
gps_moving_avg_time: 1
next_goal_to_GUI_service_name: 'next_goal_to_GUI'

# Autonomy Teleop
cmd_vel_topic: '/cmd_vel'

# Arm
sensor_arm_state_topic: 'arm/is_arm_in_home_pose'

# GPS
tf_base_link_frame: 'base_link'
tf_utm_odom_frame: 'utm_odom'
gps_odom_topic: 'utm_odom'
gq7_ekf_odom_map_topic: '/gq7/ekf/odometry_map'
gq7_ekf_llh_topic: '/gq7/ekf/llh_position'
gq7_ekf_status_topic: '/gq7/ekf/status'
crs_GPS: 'EPSG:4326'
crs_UTM: 'EPSG:3364'

# Action Lib
move_base_action_server_name: 'move_base'

# Robot
estop_enable_topic: /soft_estop/enable
estop_reset_topic: /soft_estop/reset
rover_battery_percentage_topic: /battery_level

# PXRF
start_scan_service_name: 'start_reading'
scan_recorded_to_disk_topic: 'scanned_sample'
data_dir: "~/data/pxrf_results"
pxrf_test_results_file: '~/catkin_ws/src/hebi/pxrf/scripts/chemistry.csv'

# Adaptive Algorithm
cells_per_meter: 4 

# Contant Velocity Publisher
constant_velocity_commander_service_name: '/rover/move_at_constant_velocity'
/constant_velocity/time: 1.5 # secs
/constant_velocity/cmd_vel: {
                                "linear": {"x": -0.2, "y": 0.0, "z": 0.0},
                                "angular": {"x": 0.0, "y": 0.0, "z": 0.0},
                            }
