# Autonomy Manager (autonomy_teleop.py)
status_topic: '/autonomy_manager/status'
sensor_prep_status_topic: '/sensor_prep_status'
joy_topic: '/joy'
sensor_prep_service_name: '/run_sensor_prep'
set_search_boundary_name: '/autonomy_manager/deploy_autonomy'
clear_service_name: 'clear'
waypoints_service_name: 'waypoints'
grid_points_service_name: 'grid_points'
next_goal_to_GUI_service_name: 'next_goal_to_GUI'
lower_arm_service_name: 'lower_arm'
manager_run_loop_service_name: 'manager_run_loop'
manager_run_type: 1 # 0 - continuous loop, 1 - run loop when called through service manager_run_loop_service_name
manager_set_status_after_error_param_name: 'manager/set_status_after_error'
start_utm_x_param: 'start_utm_x'
start_utm_y_param: 'start_utm_y'
start_utm_lat_param: 'start_utm_lat'
start_utm_lon_param: 'start_utm_lon'
algorithm_type_param_name: algorithm_type
algorithm_type: algo_none
algorithm_total_samples: 16

odometry_topic: 'odometry'
cancel_goal_topic: 'cancel_goal'

# GUI (gps_user_input.py)
goal_pub_topic: '/gps_navigation/goal'
gps_sub_topic: '/heading_true'
parking_break_service_name: '/parking_brake'
calibrate_start_service_name: '/start'
pxrf_client_topic_name: '/take_measurement'
gps_moving_avg_topic: '/gps_moving_avg'
gps_moving_avg_time: 1

# Autonomy Teleop (autonomy_teleop.py)
deploy_sensor_auto_service_name: '/deploy_sensor_auto'
deploy_tool_auto_service_name: '/deploy_tool_auto'
deploy_tool_service_name: '/deploy_tool'
deploy_home_auto_service_name: '/deploy_home_auto'
deploy_home_service_name: '/deploy_home'
dig_torque_topic: '/dig_torque'
cmd_vel_auto_topic: '/cmd_vel_auto'
cmd_vel_topic: '/cmd_vel'
cmd_vel_managed_topic: '/cmd_vel'

# Arm
lipo_battery_voltage_topic: 'arm/lipo_battery_voltage'
lipo_current_topic: 'arm/lipo_motor_current'
lipo_battery_refresh_interval: 30  # In secs
lower_arm_service_name: 'arm/lower'
is_arm_in_home_pose_param_name: 'arm/is_arm_in_home_pose'

# GPS
tf_base_link_frame: 'base_link'
tf_utm_odom_frame: 'utm_odom'
gps_odom_topic: 'utm_odom'
gq7_ekf_odom_map_topic: '/gq7/ekf/odometry_map'
gq7_ekf_llh_topic: '/gq7/ekf/llh_position'
gq7_ekf_status_topic: '/gq7/ekf/status'
crs_GPS: 'EPSG:4326'
crs_UTM: 'EPSG:3364'

# Action Lib
move_base_action_server_name: 'move_base'

# Network
vanta_ip: "192.168.7.2"

# Robot
estop_enable_topic: /soft_estop/enable
estop_reset_topic: /soft_estop/reset
rover_battery_voltage_topic: /rr_openrover_driver/battery_state_of_charge

# PXRF
start_scan_service_name: 'scan_start'
scan_completed_topic: 'scan_completed'
pxrf_cmd_topic: 'pxrf_cmd'
pxrf_response_topic: 'pxrf_response'
pxrf_data_topic: 'pxrf_data'
element_of_interest: 'Cl'
data_dir: "~/data/pxrf_results"
pxrf_test_results_file: '~/catkin_ws/src/hebi/pxrf/scripts/chemistry.csv'
rotate_scan_log_file_service_name: rotate_scan_log_file
autonomy_params_service_name: 'autonomy_params'
