# Autonomy Manager (autonomy_teleop.py)
status_topic: '/autonomy_manager/status'
sensor_prep_status_topic: '/sensor_prep_status'
joy_topic: '/joy'
sensor_prep_service_name: '/run_sensor_prep'
set_search_boundary_name: '/autonomy_manager/deploy_autonomy'
clear_service_name: 'clear'
waypoints_service_name: 'waypoints'
grid_points_service_name: 'grid_points'
next_goal_to_GUI_service_name: 'next_goal_to_GUI'
lower_arm_service_name: 'lower_arm'
manager_run_loop_service_name: 'manager_run_loop'
manager_run_type: 0 # 0 - continuous loop, 1 - run loop when called through service manager_run_loop_service_name

start_utm_x_param: 'start_utm_x'
start_utm_y_param: 'start_utm_y'

pxrf_cmd_topic: 'pxrf_cmd'
pxrf_response_topic: 'pxrf_response'
pxrf_data_topic: 'pxrf_data'

start_scan_service_name: 'scan_start'
pxrf_complete_service_name: 'pxrf_complete'

odometry_topic: 'odometry'
cancel_goal_topic: 'cancel_goal'

# GUI (gps_user_input.py)
goal_pub_topic: '/gps_navigation/goal'
gps_sub_topic: '/heading_true'
parking_break_service_name: '/parking_brake'
calibrate_start_service_name: '/start'
pxrf_client_topic_name: '/take_measurement'
#todo: location_sub_topic = gps_topic
location_sub_topic: '/gps_avg'

# Autonomy Teleop (autonomy_teleop.py)
deploy_sensor_auto_service_name: '/deploy_sensor_auto'
deploy_tool_auto_service_name: '/deploy_tool_auto'
deploy_tool_service_name: '/deploy_tool'
deploy_home_auto_service_name: '/deploy_home_auto'
deploy_home_service_name: '/deploy_home'
dig_torque_topic: '/dig_torque'
cmd_vel_auto_topic: '/cmd_vel_auto'
cmd_vel_topic: '/cmd_vel'
cmd_vel_managed_topic: '/cmd_vel'

# Arm
lipo_battery_voltage_topic: 'arm/lipo_battery_voltage'
lipo_current_topic: 'arm/lipo_motor_current'
lipo_battery_info_refresh_interval: 30  # In secs
lower_arm_service_name: 'arm/lower'

#GPS
tf_base_link_frame: 'base_link'
tf_utm_odom_frame: 'utm_odom'
tf_utm_odom_topic: 'utm_odom'
gq7_ekf_odom_map_topic: '/gq7/ekf/odometry_map'
gq7_ekf_llh_topic: '/gq7/ekf/llh_position'
gq7_ekf_status_topic: '/gq7/ekf/status'
crs_GPS: 'EPSG:4326'
crs_UTM: 'EPSG:3364'

# Action Lib
move_base_action_server_name: 'move_base'

# Network
vanta_ip: "192.168.7.2"